on: pull_request
jobs:
  debug-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - run: ./build.sh --registry ghcr.io --organization ${{ github.repository_owner }} --tag sha-${{ github.sha }}
      - run: docker image ls
      - run: docker push ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
