#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Publish Registry Content

on:
  workflow_run:
    workflows: ["Next Build/Publish"]
    types:
      - completed

jobs:
  publish:
    name: publish
    runs-on: ubuntu-20.04
    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: extract content
        run: |
          docker create --name pluginRegistry ghcr.io/${{ github.repository_owner }}/che-plugin-registry:next sh
          mkdir content
          docker cp pluginRegistry:/var/www/html/v3 content/v3
          docker rm -f pluginRegistry
          cp content/v3/plugins/index.json content/index.json
      - name: Publish to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_DIR: main
        run: |
          export BUILD_DIR="$PWD/content"
          export GH_PAGES_DIR="$PWD/gh-pages"
          ./build/dev/publish-plugin-registry-to-gh-pages.sh
